### ISSUE TITLE
🚀 - update README.md

### ISSUE THREAD

**Issue by TheKenkei** [routelink/client#67]
### Description

Обновить контент в  [`README.md`](https://github.com/routelink/client/blob/main/README.md)

**Comment by alextsiklis** [comment]
Могу забрать задачу на себя @olegnowikow  @TheKenkei

**Comment by alextsiklis** [comment]
[README.md](https://github.com/routelink/client/files/15067329/README.md)

Получилась пока такая сырая версия, как доделаем весь функционал, добавлю описания и гифки

**Comment by olegnowikow** [comment]
> [README.md](https://github.com/routelink/client/files/15067329/README.md)
> 
> Получилась пока такая сырая версия, как доделаем весь функционал, добавлю описания и гифки

Заливай сразу ветку, если что подправим
