### ISSUE TITLE
🐞 - fix loading animation 

### ISSUE THREAD

**Issue by SaintCAF** [routelink/client#77]
### Description

поправить анимацию загрузки при запуске страницы

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by olegnowikow** [comment]
need improve work with `cesium`
